# ethminer builder image
FROM nvidia/cuda:10.1-devel-ubuntu18.04 as builder

WORKDIR /root

RUN apt-get update \
    && apt-get install -qy build-essential git cmake perl software-properties-common mesa-common-dev libidn11-dev python3-requests python3-git

RUN git clone https://github.com/ethereum-mining/ethminer.git

RUN cd ethminer \
    && git submodule update --init --recursive \
    && mkdir build \
    && cd build \
    && cmake .. \
    && cmake --build . \
    && make install 

# ethminer distributable image image
FROM nvidia/cuda:10.1-base AS ethminer

COPY --from=builder /root/ethminer/build/ethminer/ethminer /usr/local/bin/ethminer

ENTRYPOINT ["ethminer"]

# ethminer-livepeer distributable image
FROM livepeer/go-livepeer:master AS ethminer-livepeer

COPY --from=ethminer /usr/local/bin/ethminer /usr/local/bin/ethminer
 
WORKDIR /root
COPY start.sh .
RUN chmod +x start.sh

ENTRYPOINT ["/root/start.sh"]